ktor {
    application {
        modules = [org.eyetracker.ApplicationKt.module]
    }
    deployment {
        port = 8080
        port = ${?PORT}
        host = "0.0.0.0"
    }
}

jwt {
    secret = "your-secret-key-change-me"
    secret = ${?JWT_SECRET}
    issuer = "http://0.0.0.0:8080/"
    audience = "http://0.0.0.0:8080/"
    realm = "Access to the API"
}

storage {
    uploadDir = "uploads"
    uploadDir = ${?UPLOAD_DIR}
}

database {
    url = "jdbc:postgresql://postgres:5432/postgres"
    url = ${?DATABASE_URL}
    driver = "org.postgresql.Driver"
    user = "postgres"
    user = ${?DATABASE_USER}
    password = "my-secret-pw"
    password = ${?DATABASE_PASSWORD}
}
